# Generated by Django 4.1 on 2023-08-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="u_nickname",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="counselor",
            name="c_certificate",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="counselor/certificate",
                verbose_name="썸네일 이미지",
            ),
        ),
    ]
