# Generated by Django 4.1 on 2023-08-29 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat_message",
            name="m_room",
        ),
        migrations.RemoveField(
            model_name="chat_room",
            name="r_article",
        ),
        migrations.AlterField(
            model_name="chat_message",
            name="m_content",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="chat_message",
            name="m_writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chat_room",
            name="r_counselor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.counselor",
            ),
        ),
        migrations.AlterField(
            model_name="chat_room",
            name="r_patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.patient",
            ),
        ),
    ]
