# Generated by Django 4.1 on 2023-08-18 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_title", models.CharField(max_length=200)),
                ("a_content", models.CharField(max_length=200)),
                (
                    "a_published_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "a_tree_image",
                    models.ImageField(
                        blank=True, upload_to="htp/tree", verbose_name="나무 이미지"
                    ),
                ),
                (
                    "a_man_image",
                    models.ImageField(
                        blank=True, upload_to="htp/man", verbose_name="남자사람 이미지"
                    ),
                ),
                (
                    "a_woman_image",
                    models.ImageField(
                        blank=True, upload_to="htp/woman", verbose_name="여자사람 이미지"
                    ),
                ),
                (
                    "a_house_image",
                    models.ImageField(
                        blank=True, upload_to="htp/house", verbose_name="집 이미지"
                    ),
                ),
                (
                    "a_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CounselorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_rating", models.FloatField()),
                (
                    "r_counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.counselor",
                    ),
                ),
                (
                    "r_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_content", models.CharField(max_length=200)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.article"
                    ),
                ),
                (
                    "c_commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
