# Generated by Django 4.1 on 2023-08-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentalstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggression", models.IntegerField(null=True)),
                ("anxiety", models.IntegerField(null=True)),
                ("dependency", models.IntegerField(null=True)),
                ("stress", models.IntegerField(null=True)),
                ("timidity", models.IntegerField(null=True)),
                ("sociability", models.IntegerField(null=True)),
                ("depression", models.IntegerField(null=True)),
                ("independence", models.IntegerField(null=True)),
                ("achievement", models.IntegerField(null=True)),
                ("selfish", models.IntegerField(null=True)),
                (
                    "m_article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="board.article"
                    ),
                ),
            ],
        ),
    ]
